# Server Configuration
server:
  port: 8080

spring:
  application:
    name: ecom-service
  
  # Database Configuration (Default - H2 for development)
  datasource:
    url: jdbc:h2:mem:ecom_service
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.iavtar: DEBUG
  pattern:
    console: "[ecom-service] %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"